# Copyright 2024-2026 Samsarix LLC
# SPDX-License-Identifier: Apache-2.0

"""Public API for the Samsarix Agent Ethics policy gate."""

from .approval import (
    MAX_TOOL_CALL_FINGERPRINT_BYTES,
    TOOL_CALL_APPROVAL_VERSION,
    TOOL_CALL_FINGERPRINT_VERSION,
    ToolCallApproval,
)
from .audit import AUDIT_RECORD_VERSION, AuditRecord, AuditSink, JsonlAuditSink
from .comparison import (
    POLICY_COMPARISON_VERSION,
    PolicyComparisonChange,
    PolicyComparisonReport,
    PolicyComparisonResult,
    PolicyComparisonSnapshot,
    PolicyComparisonStatus,
    compare_policies,
)
from .composition import (
    MAX_COMPOSED_POLICIES,
    POLICY_COMPOSITION_VERSION,
    PolicyComposition,
    PolicyCompositionSource,
    compose_policies,
)
from .contracts import (
    CONTEXT_CONTRACT_VERSION,
    MAX_CONTEXT_CONTRACT_FIELDS,
    ContextContract,
    ContextField,
    ContextFieldType,
    validate_context_against_contract,
    validate_policy_context_contract,
)
from .coverage import (
    POLICY_COVERAGE_VERSION,
    PolicyCoverageError,
    PolicyCoverageReport,
    measure_policy_coverage,
)
from .deployment import (
    DEPLOYMENT_LOCK_VERSION,
    DeploymentLock,
    DeploymentLockArtifact,
    create_deployment_lock,
    verify_deployment_lock,
)
from .diagnostics import (
    POLICY_LINT_VERSION,
    PolicyLintCode,
    PolicyLintFinding,
    PolicyLintReport,
    PolicyLintSeverity,
    lint_policy,
)
from .engine import MAX_BATCH_ITEMS, PolicyEngine
from .errors import (
    AuditLogError,
    ContextContractValidationError,
    DeploymentLockValidationError,
    EvaluationError,
    InputValidationError,
    PolicyActivationError,
    PolicyCompositionError,
    PolicyDeploymentValidationError,
    PolicyTestValidationError,
    PolicyValidationError,
    SamsarixEthicsError,
    ToolCallBlockedError,
    ToolCallDeniedError,
    ToolCallReviewRequiredError,
)
from .explanation import (
    POLICY_EXPLANATION_VERSION,
    ConditionExplanation,
    ConditionExplanationStatus,
    PolicyExplanation,
    RuleExplanation,
)
from .gate import (
    MAX_TOOL_CAPABILITIES,
    TOOL_CONTEXT_VERSION,
    BoundToolGate,
    ToolExecutionResult,
    ToolGate,
    build_tool_context,
    fingerprint_tool_call,
)
from .io import (
    MAX_CONTEXT_CONTRACT_BYTES,
    MAX_DEPLOYMENT_LOCK_BYTES,
    MAX_POLICY_DEPLOYMENT_BYTES,
    append_audit_record,
    load_context,
    load_context_contract,
    load_deployment_lock,
    load_policy,
    load_policy_deployment,
    write_policy,
    write_policy_deployment,
)
from .models import MAX_POLICY_RULES, Decision, Effect, Outcome, Policy, PolicyCondition, PolicyRule
from .policy_deployment import (
    POLICY_DEPLOYMENT_VERSION,
    PolicyDeployment,
    create_policy_deployment,
)
from .provenance import (
    CONTEXT_CONTRACT_FINGERPRINT_VERSION,
    POLICY_FINGERPRINT_VERSION,
    fingerprint_context_contract,
    fingerprint_policy,
)
from .runtime import POLICY_RUNTIME_STATUS_VERSION, PolicyRuntime, PolicyRuntimeStatus
from .schema import (
    get_audit_record_schema,
    get_context_contract_schema,
    get_deployment_lock_schema,
    get_policy_comparison_schema,
    get_policy_composition_schema,
    get_policy_coverage_schema,
    get_policy_deployment_schema,
    get_policy_explanation_schema,
    get_policy_lint_schema,
    get_policy_runtime_status_schema,
    get_policy_schema,
    get_policy_shadow_schema,
    get_policy_test_schema,
    get_tool_approval_schema,
    get_tool_context_schema,
)
from .shadow import (
    POLICY_SHADOW_VERSION,
    PolicyShadowChange,
    PolicyShadowEvaluation,
    PolicyShadowEvaluator,
    PolicyShadowSnapshot,
    PolicyShadowStatus,
)
from .testing import (
    MAX_POLICY_TEST_BYTES,
    PolicyTestCase,
    PolicyTestReport,
    PolicyTestResult,
    PolicyTestStatus,
    PolicyTestSuite,
    load_policy_test_suite,
    run_policy_tests,
)
from .validation import validate_context

__version__ = "0.1.0"

__all__ = [
    "AUDIT_RECORD_VERSION",
    "CONTEXT_CONTRACT_FINGERPRINT_VERSION",
    "CONTEXT_CONTRACT_VERSION",
    "DEPLOYMENT_LOCK_VERSION",
    "MAX_BATCH_ITEMS",
    "MAX_COMPOSED_POLICIES",
    "MAX_CONTEXT_CONTRACT_BYTES",
    "MAX_CONTEXT_CONTRACT_FIELDS",
    "MAX_DEPLOYMENT_LOCK_BYTES",
    "MAX_POLICY_DEPLOYMENT_BYTES",
    "MAX_POLICY_RULES",
    "MAX_POLICY_TEST_BYTES",
    "MAX_TOOL_CALL_FINGERPRINT_BYTES",
    "MAX_TOOL_CAPABILITIES",
    "POLICY_COMPARISON_VERSION",
    "POLICY_COMPOSITION_VERSION",
    "POLICY_COVERAGE_VERSION",
    "POLICY_DEPLOYMENT_VERSION",
    "POLICY_EXPLANATION_VERSION",
    "POLICY_FINGERPRINT_VERSION",
    "POLICY_LINT_VERSION",
    "POLICY_RUNTIME_STATUS_VERSION",
    "POLICY_SHADOW_VERSION",
    "TOOL_CALL_APPROVAL_VERSION",
    "TOOL_CALL_FINGERPRINT_VERSION",
    "TOOL_CONTEXT_VERSION",
    "AuditLogError",
    "AuditRecord",
    "AuditSink",
    "BoundToolGate",
    "ConditionExplanation",
    "ConditionExplanationStatus",
    "ContextContract",
    "ContextContractValidationError",
    "ContextField",
    "ContextFieldType",
    "Decision",
    "DeploymentLock",
    "DeploymentLockArtifact",
    "DeploymentLockValidationError",
    "Effect",
    "EvaluationError",
    "InputValidationError",
    "JsonlAuditSink",
    "Outcome",
    "Policy",
    "PolicyActivationError",
    "PolicyComparisonChange",
    "PolicyComparisonReport",
    "PolicyComparisonResult",
    "PolicyComparisonSnapshot",
    "PolicyComparisonStatus",
    "PolicyComposition",
    "PolicyCompositionError",
    "PolicyCompositionSource",
    "PolicyCondition",
    "PolicyCoverageError",
    "PolicyCoverageReport",
    "PolicyDeployment",
    "PolicyDeploymentValidationError",
    "PolicyEngine",
    "PolicyExplanation",
    "PolicyLintCode",
    "PolicyLintFinding",
    "PolicyLintReport",
    "PolicyLintSeverity",
    "PolicyRule",
    "PolicyRuntime",
    "PolicyRuntimeStatus",
    "PolicyShadowChange",
    "PolicyShadowEvaluation",
    "PolicyShadowEvaluator",
    "PolicyShadowSnapshot",
    "PolicyShadowStatus",
    "PolicyTestCase",
    "PolicyTestReport",
    "PolicyTestResult",
    "PolicyTestStatus",
    "PolicyTestSuite",
    "PolicyTestValidationError",
    "PolicyValidationError",
    "RuleExplanation",
    "SamsarixEthicsError",
    "ToolCallApproval",
    "ToolCallBlockedError",
    "ToolCallDeniedError",
    "ToolCallReviewRequiredError",
    "ToolExecutionResult",
    "ToolGate",
    "append_audit_record",
    "build_tool_context",
    "compare_policies",
    "compose_policies",
    "create_deployment_lock",
    "create_policy_deployment",
    "fingerprint_context_contract",
    "fingerprint_policy",
    "fingerprint_tool_call",
    "get_audit_record_schema",
    "get_context_contract_schema",
    "get_deployment_lock_schema",
    "get_policy_comparison_schema",
    "get_policy_composition_schema",
    "get_policy_coverage_schema",
    "get_policy_deployment_schema",
    "get_policy_explanation_schema",
    "get_policy_lint_schema",
    "get_policy_runtime_status_schema",
    "get_policy_schema",
    "get_policy_shadow_schema",
    "get_policy_test_schema",
    "get_tool_approval_schema",
    "get_tool_context_schema",
    "lint_policy",
    "load_context",
    "load_context_contract",
    "load_deployment_lock",
    "load_policy",
    "load_policy_deployment",
    "load_policy_test_suite",
    "measure_policy_coverage",
    "run_policy_tests",
    "validate_context",
    "validate_context_against_contract",
    "validate_policy_context_contract",
    "verify_deployment_lock",
    "write_policy",
    "write_policy_deployment",
]
