"""Published/imported package-shape tests."""

from __future__ import annotations

import samsarix_ethics


def test_public_api_is_importable() -> None:
    assert samsarix_ethics.__version__ == "0.1.0"
    assert samsarix_ethics.PolicyEngine.__module__ == "samsarix_ethics.engine"
    assert "PolicyValidationError" in samsarix_ethics.__all__
    assert "SamsarixEthicsError" in samsarix_ethics.__all__
    assert "validate_context" in samsarix_ethics.__all__
    assert "ContextContract" in samsarix_ethics.__all__
    assert "ContextContractValidationError" in samsarix_ethics.__all__
    assert "get_context_contract_schema" in samsarix_ethics.__all__
    assert "load_context_contract" in samsarix_ethics.__all__
    assert "validate_policy_context_contract" in samsarix_ethics.__all__
    assert "ToolGate" in samsarix_ethics.__all__
    assert "BoundToolGate" in samsarix_ethics.__all__
    assert "BoundToolCatalog" in samsarix_ethics.__all__
    assert "ToolCatalog" in samsarix_ethics.__all__
    assert "ToolCatalogEntry" in samsarix_ethics.__all__
    assert "ToolCatalogValidationError" in samsarix_ethics.__all__
    assert "ToolCallback" in samsarix_ethics.__all__
    assert "ToolDispatcher" in samsarix_ethics.__all__
    assert "LangChainIntegrationError" in samsarix_ethics.__all__
    assert "LangChainToolPolicy" in samsarix_ethics.__all__
    assert "create_langchain_tool_policy" in samsarix_ethics.__all__
    assert "OpenAIAgentsApprovalStore" in samsarix_ethics.__all__
    assert "OpenAIAgentsIntegrationError" in samsarix_ethics.__all__
    assert "OpenAIAgentsToolPolicy" in samsarix_ethics.__all__
    assert "create_openai_agents_tool_policy" in samsarix_ethics.__all__
    assert "PydanticAIIntegrationError" in samsarix_ethics.__all__
    assert "PydanticAIToolPolicy" in samsarix_ethics.__all__
    assert "create_pydantic_ai_tool_policy" in samsarix_ethics.__all__
    assert "OpenTelemetryDecisionEventSink" in samsarix_ethics.__all__
    assert "OpenTelemetryIntegrationError" in samsarix_ethics.__all__
    assert "CompositeAuditSink" in samsarix_ethics.__all__
    assert "load_tool_catalog" in samsarix_ethics.__all__
    assert "fingerprint_tool_catalog" in samsarix_ethics.__all__
    assert "validate_tool_catalog_registration" in samsarix_ethics.__all__
    assert "get_tool_catalog_schema" in samsarix_ethics.__all__
    assert "ToolGateDeployment" in samsarix_ethics.__all__
    assert "ToolGateDeploymentValidationError" in samsarix_ethics.__all__
    assert "create_tool_gate_deployment" in samsarix_ethics.__all__
    assert "load_tool_gate_deployment" in samsarix_ethics.__all__
    assert "write_tool_gate_deployment" in samsarix_ethics.__all__
    assert "get_tool_gate_deployment_schema" in samsarix_ethics.__all__
    assert "ToolGateDeploymentEnvelope" in samsarix_ethics.__all__
    assert "VerifiedToolGateDeployment" in samsarix_ethics.__all__
    assert "DeploymentAuthenticationError" in samsarix_ethics.__all__
    assert "authenticate_tool_gate_deployment" in samsarix_ethics.__all__
    assert "generate_deployment_auth_key" in samsarix_ethics.__all__
    assert "verify_tool_gate_deployment_envelope" in samsarix_ethics.__all__
    assert "load_tool_gate_deployment_envelope" in samsarix_ethics.__all__
    assert "write_tool_gate_deployment_envelope" in samsarix_ethics.__all__
    assert "get_tool_gate_deployment_envelope_schema" in samsarix_ethics.__all__
    assert "fingerprint_tool_gate_deployment" in samsarix_ethics.__all__
    assert "PreparedToolCall" in samsarix_ethics.__all__
    assert "ToolCallBlockedError" in samsarix_ethics.__all__
    assert "get_tool_context_schema" in samsarix_ethics.__all__
    assert "get_tool_approval_schema" in samsarix_ethics.__all__
    assert "get_audit_record_schema" in samsarix_ethics.__all__
    assert "AuditRecord" in samsarix_ethics.__all__
    assert "AuditChainEntry" in samsarix_ethics.__all__
    assert "AuditChainError" in samsarix_ethics.__all__
    assert "AuditChainVerification" in samsarix_ethics.__all__
    assert "HmacAuditChainSink" in samsarix_ethics.__all__
    assert "generate_audit_chain_key" in samsarix_ethics.__all__
    assert "verify_audit_chain" in samsarix_ethics.__all__
    assert "get_audit_chain_entry_schema" in samsarix_ethics.__all__
    assert "get_audit_chain_verification_schema" in samsarix_ethics.__all__
    assert "ToolCallApproval" in samsarix_ethics.__all__
    assert "fingerprint_tool_call" in samsarix_ethics.__all__
    assert "fingerprint_policy" in samsarix_ethics.__all__
    assert "fingerprint_context_contract" in samsarix_ethics.__all__
    assert "DeploymentLock" in samsarix_ethics.__all__
    assert "DeploymentLockArtifact" in samsarix_ethics.__all__
    assert "DeploymentLockValidationError" in samsarix_ethics.__all__
    assert "create_deployment_lock" in samsarix_ethics.__all__
    assert "verify_deployment_lock" in samsarix_ethics.__all__
    assert "load_deployment_lock" in samsarix_ethics.__all__
    assert "get_deployment_lock_schema" in samsarix_ethics.__all__
    assert "PolicyDeployment" in samsarix_ethics.__all__
    assert "PolicyDeploymentValidationError" in samsarix_ethics.__all__
    assert "create_policy_deployment" in samsarix_ethics.__all__
    assert "load_policy_deployment" in samsarix_ethics.__all__
    assert "write_policy_deployment" in samsarix_ethics.__all__
    assert "get_policy_deployment_schema" in samsarix_ethics.__all__
    assert "compare_policies" in samsarix_ethics.__all__
    assert "compose_policies" in samsarix_ethics.__all__
    assert "PolicyComposition" in samsarix_ethics.__all__
    assert "PolicyCompositionError" in samsarix_ethics.__all__
    assert "PolicyCompositionSource" in samsarix_ethics.__all__
    assert "PolicyComparisonReport" in samsarix_ethics.__all__
    assert "measure_policy_coverage" in samsarix_ethics.__all__
    assert "PolicyCoverageReport" in samsarix_ethics.__all__
    assert "PolicyExplanation" in samsarix_ethics.__all__
    assert "RuleExplanation" in samsarix_ethics.__all__
    assert "ConditionExplanation" in samsarix_ethics.__all__
    assert "ConditionExplanationStatus" in samsarix_ethics.__all__
    assert "get_policy_explanation_schema" in samsarix_ethics.__all__
    assert "PolicyRuntime" in samsarix_ethics.__all__
    assert "PolicyRuntimeStatus" in samsarix_ethics.__all__
    assert "PolicyActivationError" in samsarix_ethics.__all__
    assert "get_policy_runtime_status_schema" in samsarix_ethics.__all__
    assert "lint_policy" in samsarix_ethics.__all__
    assert "PolicyLintReport" in samsarix_ethics.__all__
    assert "PolicyShadowEvaluator" in samsarix_ethics.__all__
    assert "PolicyShadowEvaluation" in samsarix_ethics.__all__
    assert "get_policy_comparison_schema" in samsarix_ethics.__all__
    assert "get_policy_composition_schema" in samsarix_ethics.__all__
    assert "get_policy_shadow_schema" in samsarix_ethics.__all__
    assert samsarix_ethics.MAX_BATCH_ITEMS == 1_000
    assert samsarix_ethics.MAX_POLICY_RULES == 1_000
    assert samsarix_ethics.MAX_TOOL_CAPABILITIES == 64
    assert samsarix_ethics.MAX_TOOL_BATCH_ITEMS == 1_000
    assert samsarix_ethics.MAX_TOOL_CALL_FINGERPRINT_BYTES == 1_048_576
    assert samsarix_ethics.MAX_PENDING_OPENAI_APPROVALS == 4_096
    assert samsarix_ethics.LANGCHAIN_ADAPTER_VERSION == 1
    assert samsarix_ethics.LANGCHAIN_REVIEW_INTERRUPT_TYPE == "samsarix.tool_call.review"
    assert samsarix_ethics.OPENAI_AGENTS_ADAPTER_VERSION == 1
    assert samsarix_ethics.PYDANTIC_AI_ADAPTER_VERSION == 1
    assert samsarix_ethics.PYDANTIC_AI_APPROVAL_METADATA_KEY == "samsarix.tool_call.approval"
    assert samsarix_ethics.PYDANTIC_AI_REVIEW_METADATA_KEY == "samsarix.tool_call.review"
    assert samsarix_ethics.OPENTELEMETRY_DECISION_EVENT_NAME == "samsarix.policy.decision"
    assert samsarix_ethics.OPENTELEMETRY_DECISION_EVENT_VERSION == 1
    assert samsarix_ethics.MAX_COMPOSITE_AUDIT_SINKS == 32
    assert samsarix_ethics.POLICY_FINGERPRINT_VERSION == 1
    assert samsarix_ethics.POLICY_COMPARISON_VERSION == 1
    assert samsarix_ethics.POLICY_COMPOSITION_VERSION == 1
    assert samsarix_ethics.POLICY_COVERAGE_VERSION == 1
    assert samsarix_ethics.POLICY_EXPLANATION_VERSION == 1
    assert samsarix_ethics.POLICY_LINT_VERSION == 1
    assert samsarix_ethics.POLICY_RUNTIME_STATUS_VERSION == 1
    assert samsarix_ethics.POLICY_SHADOW_VERSION == 1
    assert samsarix_ethics.TOOL_CALL_APPROVAL_VERSION == 1
    assert samsarix_ethics.TOOL_CALL_FINGERPRINT_VERSION == 1
    assert samsarix_ethics.TOOL_CONTEXT_VERSION == 1
    assert samsarix_ethics.TOOL_CATALOG_VERSION == 1
    assert samsarix_ethics.TOOL_CATALOG_FINGERPRINT_VERSION == 1
    assert samsarix_ethics.TOOL_GATE_DEPLOYMENT_VERSION == 1
    assert samsarix_ethics.TOOL_GATE_DEPLOYMENT_AUTH_VERSION == 1
    assert samsarix_ethics.TOOL_GATE_DEPLOYMENT_FINGERPRINT_VERSION == 1
    assert samsarix_ethics.MIN_DEPLOYMENT_AUTH_KEY_BYTES == 32
    assert samsarix_ethics.MAX_DEPLOYMENT_AUTH_KEY_BYTES == 4_096
    assert samsarix_ethics.MAX_DEPLOYMENT_AUTH_KEYS == 32
    assert samsarix_ethics.MAX_DEPLOYMENT_AUTH_LIFETIME_SECONDS == 2_592_000
    assert samsarix_ethics.MAX_DEPLOYMENT_AUTH_CLOCK_SKEW_SECONDS == 3_600
    assert samsarix_ethics.MAX_DEPLOYMENT_AUTH_SEQUENCE == 9_223_372_036_854_775_807
    assert samsarix_ethics.AUDIT_RECORD_VERSION == 1
    assert samsarix_ethics.AUDIT_CHAIN_VERSION == 1
    assert samsarix_ethics.AUDIT_CHAIN_VERIFICATION_VERSION == 1
    assert samsarix_ethics.MIN_AUDIT_CHAIN_KEY_BYTES == 32
    assert samsarix_ethics.MAX_AUDIT_CHAIN_KEY_BYTES == 4_096
    assert samsarix_ethics.MAX_AUDIT_CHAIN_BYTES == 1_073_741_824
    assert samsarix_ethics.MAX_AUDIT_CHAIN_ENTRY_BYTES == 262_144
    assert samsarix_ethics.MAX_AUDIT_CHAIN_ENTRIES == 1_000_000
    assert samsarix_ethics.CONTEXT_CONTRACT_VERSION == 1
    assert samsarix_ethics.CONTEXT_CONTRACT_FINGERPRINT_VERSION == 1
    assert samsarix_ethics.DEPLOYMENT_LOCK_VERSION == 1
    assert samsarix_ethics.POLICY_DEPLOYMENT_VERSION == 1
    assert samsarix_ethics.MAX_DEPLOYMENT_LOCK_BYTES == 65_536
    assert samsarix_ethics.MAX_CONTEXT_CONTRACT_FIELDS == 1_000
    assert samsarix_ethics.MAX_POLICY_DEPLOYMENT_BYTES == 4_194_304
    assert samsarix_ethics.MAX_TOOL_CATALOG_BYTES == 262_144
    assert samsarix_ethics.MAX_TOOL_CATALOG_CAPABILITIES == 64
    assert samsarix_ethics.MAX_TOOL_CATALOG_TOOLS == 256
    assert samsarix_ethics.MAX_TOOL_GATE_DEPLOYMENT_BYTES == 4_718_592
    assert samsarix_ethics.MAX_TOOL_GATE_DEPLOYMENT_ENVELOPE_BYTES == 5_242_880
